version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: hospital_inventory_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: hospital_inventory
      POSTGRES_USER: hospital_user
      POSTGRES_PASSWORD: hospital_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hospital_user -d hospital_inventory"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
