# Generated by Django 4.2.21 on 2025-05-26 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='added_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_stock_items', to=settings.AUTH_USER_MODEL, verbose_name='Added By'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_stock_items', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Select the category for this item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='warehouse.stockitemcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='For perishable items. Leave blank if not applicable.', null=True, verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='item_id',
            field=models.CharField(help_text='Unique identifier for the stock item (e.g., SKU, part number).', max_length=50, unique=True, verbose_name='Item ID / SKU'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='last_restocked_date',
            field=models.DateField(blank=True, help_text='Date when the item was last restocked.', null=True, verbose_name='Last Restocked Date'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='minimum_stock_level',
            field=models.PositiveIntegerField(default=1, help_text='Minimum quantity before reordering is needed.', verbose_name='Minimum Stock Level'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='name',
            field=models.CharField(help_text='Name of the stock item (e.g., USB-C Cable, HP 85A Toner Cartridge).', max_length=200, verbose_name='Item Name'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Any additional notes about this stock item.', null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='quantity_on_hand',
            field=models.PositiveIntegerField(default=0, help_text='Current quantity in stock.', verbose_name='Quantity on Hand'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='storage_location',
            field=models.CharField(blank=True, help_text='Physical location in the warehouse (e.g., Shelf A1, Bin 3).', max_length=100, null=True, verbose_name='Storage Location'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Select the supplier for this item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_stock_items', to='warehouse.stockitemsupplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per unit. Enter 0 if not applicable or free.', max_digits=10, null=True, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='stockitemcategory',
            name='description',
            field=models.TextField(blank=True, help_text='Optional: A brief description of the category.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='stockitemcategory',
            name='name',
            field=models.CharField(help_text='Category of the stock item (e.g., Cables, Toners, Peripherals).', max_length=100, unique=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='stockitemsupplier',
            name='address',
            field=models.TextField(blank=True, help_text='Full address of the supplier.', null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='stockitemsupplier',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Primary contact person at the supplier.', max_length=100, null=True, verbose_name='Contact Person'),
        ),
        migrations.AlterField(
            model_name='stockitemsupplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='stockitemsupplier',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Supplier Name'),
        ),
        migrations.AlterField(
            model_name='stockitemsupplier',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
    ]
