# Generated by Django 4.2.21 on 2025-05-26 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requests_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-created_at'], 'verbose_name': 'IT Service Request', 'verbose_name_plural': 'IT Service Requests'},
        ),
        migrations.AlterModelOptions(
            name='requesttype',
            options={'verbose_name': 'Request Type', 'verbose_name_plural': 'Request Types'},
        ),
        migrations.AlterModelOptions(
            name='requestupdate',
            options={'ordering': ['-update_time'], 'verbose_name': 'Request Update', 'verbose_name_plural': 'Request Updates'},
        ),
        migrations.RenameField(
            model_name='request',
            old_name='requested_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='request',
            name='closed_at',
        ),
        migrations.RemoveField(
            model_name='request',
            name='request_id',
        ),
        migrations.RemoveField(
            model_name='request',
            name='resolution_details',
        ),
        migrations.RemoveField(
            model_name='request',
            name='title',
        ),
        migrations.RemoveField(
            model_name='requestupdate',
            name='is_internal_note',
        ),
        migrations.RemoveField(
            model_name='requestupdate',
            name='update_text',
        ),
        migrations.RemoveField(
            model_name='requestupdate',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='request',
            name='resolution_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='subject',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestupdate',
            name='new_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='requestupdate',
            name='notes',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestupdate',
            name='old_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='requestupdate',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='request',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='related_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to='inventory.equipment'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='requesttype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requesttype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
