# Generated by Django 4.2.21 on 2025-05-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0004_alter_request_options_alter_requesttype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-created_at'], 'permissions': [('can_assign_request', 'Can assign IT requests to staff'), ('can_change_request_status', 'Can change status of IT requests'), ('can_view_all_requests', 'Can view all IT requests'), ('can_close_request', 'Can close/reopen own IT requests as user')], 'verbose_name': 'IT Request', 'verbose_name_plural': 'IT Requests'},
        ),
        migrations.AlterField(
            model_name='request',
            name='date_assigned',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date Assigned'),
        ),
        migrations.AlterField(
            model_name='request',
            name='resolved_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date Resolved/Closed'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('pending_user_input', 'Pending User Input'), ('pending_order', 'Pending Order'), ('pending_third_party', 'Pending Third Party'), ('awaiting_parts', 'Awaiting Parts'), ('scheduled_maintenance', 'Scheduled Maintenance'), ('on_hold', 'On Hold (General)'), ('reopened', 'Reopened'), ('completed', 'Completed'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='new', help_text='Current status of the request.', max_length=25, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='requestupdate',
            name='new_status',
            field=models.CharField(blank=True, help_text='Status after this update.', max_length=25, null=True, verbose_name='New Status'),
        ),
        migrations.AlterField(
            model_name='requestupdate',
            name='old_status',
            field=models.CharField(blank=True, help_text='Status before this update.', max_length=25, null=True, verbose_name='Old Status'),
        ),
    ]
