# Generated by Django 4.2.21 on 2025-05-26 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0003_alter_equipment_added_by_alter_equipment_date_added_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['name'], 'verbose_name': 'Status', 'verbose_name_plural': 'Statuses'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers'},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Optional: A brief description of the category.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text="Font Awesome icon class (e.g., 'fas fa-laptop'). Search icons at fontawesome.com.", max_length=50, null=True, verbose_name='Icon Class'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='e.g., Laptops, Printers, Monitors', max_length=100, unique=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='added_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_equipment', to=settings.AUTH_USER_MODEL, verbose_name='Added By'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='asset_tag',
            field=models.CharField(help_text='Unique internal identifier for tracking the equipment.', max_length=50, unique=True, verbose_name='Asset Tag'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='User to whom this equipment is currently assigned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_equipment', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Select the category this equipment belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='inventory.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='current_location',
            field=models.ForeignKey(blank=True, help_text='Where the equipment is currently located.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_at_location', to='inventory.location', verbose_name='Current Location'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(help_text='Descriptive name of the equipment (e.g., Dell Latitude 5590).', max_length=200, verbose_name='Equipment Name'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='notes',
            field=models.TextField(blank=True, help_text='Any additional notes or comments about the equipment.', null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='purchase_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost of the equipment at the time of purchase.', max_digits=10, null=True, verbose_name='Purchase Cost'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='purchase_date',
            field=models.DateField(blank=True, help_text='Date when the equipment was purchased.', null=True, verbose_name='Purchase Date'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(blank=True, help_text="Manufacturer's serial number. Leave blank if not available or applicable.", max_length=100, null=True, unique=True, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.ForeignKey(help_text='Current status of the equipment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='inventory.status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Supplier from whom this equipment was purchased.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_equipment', to='inventory.supplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_equipment', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, help_text="Date when the manufacturer's warranty expires.", null=True, verbose_name='Warranty Expiry Date'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, help_text='Physical address of the location, if applicable.', max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='location',
            name='floor',
            field=models.CharField(blank=True, help_text='Floor number or name.', max_length=50, null=True, verbose_name='Floor'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(help_text='e.g., Main Building, West Wing, IT Department', max_length=100, unique=True, verbose_name='Location Name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='notes',
            field=models.TextField(blank=True, help_text='Any additional notes about this location.', null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='location',
            name='room_number',
            field=models.CharField(blank=True, help_text='Specific room number or name within the location.', max_length=50, null=True, verbose_name='Room Number/Name'),
        ),
        migrations.AlterField(
            model_name='status',
            name='description',
            field=models.TextField(blank=True, help_text='Optional: A brief description of the status.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='status',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates if this status means the equipment is actively usable.', verbose_name='Is Active Status'),
        ),
        migrations.AlterField(
            model_name='status',
            name='is_decommissioned',
            field=models.BooleanField(default=False, help_text='Designates if this status means the equipment is permanently out of service.', verbose_name='Is Decommissioned Status'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(help_text='e.g., In Use, In Storage, Under Repair, Decommissioned', max_length=50, unique=True, verbose_name='Status Name'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Primary contact person at the supplier.', max_length=100, null=True, verbose_name='Contact Person'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Supplier Name'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='notes',
            field=models.TextField(blank=True, help_text='Any additional notes about this supplier.', null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website URL'),
        ),
    ]
