# Generated by Django 4.2.21 on 2025-05-28 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stockitem_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='category',
            field=models.ForeignKey(blank=True, help_text='აირჩიეთ ამ სტოკის ერთეულის ზოგადი კატეგორია.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='inventory.category', verbose_name='General Category (Optional)'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='storage_location',
            field=models.ForeignKey(blank=True, help_text='აირჩიეთ ფიზიკური ლოკაცია, სადაც ეს სტოკის ერთეული ინახება.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items_at_location', to='inventory.location', verbose_name='Storage Location (Optional)'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Transaction Notes or Reference'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='quantity_changed',
            field=models.IntegerField(help_text='Positive for additions, negative for removals.', verbose_name='Quantity Changed'),
        ),
    ]
