# Generated by Django 4.2.21 on 2025-05-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_equipment_asset_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='is_marked_for_write_off',
            field=models.BooleanField(default=False, help_text='აღნიშნავს, რომ ამ სტატუსის მქონე ტექნიკა მონიშნულია ჩამოსაწერად, მაგრამ ჯერ არ არის საბოლოოდ ჩამოწერილი.', verbose_name='Is Marked for Write-Off'),
        ),
        migrations.AlterField(
            model_name='equipmentlog',
            name='change_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('field_change', 'Field Changed'), ('status_changed', 'Status Changed'), ('location_changed', 'Location Changed'), ('assigned', 'Assigned/Unassigned'), ('marked_for_write_off', 'Marked for Write-Off'), ('decommissioned', 'Decommissioned'), ('restored', 'Restored from Decommission'), ('archived', 'Archived'), ('notes_added', 'Notes Added/Changed'), ('maintenance_log', 'Maintenance Logged'), ('warranty_updated', 'Warranty Info Updated'), ('other', 'Other')], default='updated', max_length=30, verbose_name='Type of Change'),
        ),
    ]
